- name: Add ZeroTier gpg key
  rpm_key:
    state: present
    key: "{{ zerotier_gpg_url }}"

- name: Add ZeroTier repo
  yum_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    baseurl: https://download.zerotier.com/redhat/el/$releasever
    gpgcheck: yes
    enabled: yes
  register: zerotier_repo
