---
- block: # Add zerotier repo and it's gpg key
  - name: Add zerotier gpg key
    rpm_key:
      state: present
      key: https://download.zerotier.com/contact%40zerotier.com.gpg

  - name: Add zerotier repo
    yum_repository:
      name: zerotier
      description: ZeroTier, Inc. RPM Release Repository
      baseurl: https://download.zerotier.com/redhat/el/$releasever
      gpgcheck: yes
      enabled: yes
    register: zerotier_repo

  tags:
  - installation
  - repositories

- block: #Install and enable zerotier-one
  - name: Install zerotier-one
    package:
      name: zerotier-one
      state: present
    register: zerotier_client

  - name: Start zerotier-one service
    service:
      name: zerotier-one
      state: started
    when:
    - zerotier_client|succeeded
    notify:
    - enable zerotier-one

  when:
  - zerotier_repo|succeeded
  tags:
  - installation
  - packages
