---
# tasks file for ansible-role-zerotier
- import_tasks: install.yml
  when:
  - "'zt0' not in ansible_interfaces"

- import_tasks: authorize_node.yml
  when:
  - zerotier_accesstoken is defined

- import_tasks: join_network.yml
  when:
  - zerotier_network_id is defined
